Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 100.10.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: vpc_pro